Створіть одновимірний масив (вектор) з перших 10 піднесених до квадрату
натуральних чисел та виведіть його значення

In [1]:
import numpy as np

vector = np.array([i**2 for i in range(1, 11)])

print(vector)


[  1   4   9  16  25  36  49  64  81 100]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
квадратних коренів від кожного натурального числа, починаючи з 1, та виведіть його
значення

In [2]:
import numpy as np

matrix = np.array([[np.sqrt(i) for i in range(j, j + 3)] for j in range(1, 10, 3)])

print(matrix)


[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


Створіть масив розміром 3x3, заповніть його випадковими цілими числами в діапазоні
від 0 до 5 та виведіть його значення.

In [4]:
import numpy as np

random_matrix = np.random.randint(0, 6, (3, 3))

print(random_matrix)


[[0 0 0]
 [3 0 3]
 [3 1 1]]


Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та обчисліть суму елементів, які менше середнього значення.


In [5]:
import numpy as np

random_matrix_5x5 = np.random.rand(5, 5)

mean_value = np.mean(random_matrix_5x5)

sum_below_mean = np.sum(random_matrix_5x5[random_matrix_5x5 < mean_value])

print("Масив:")
print(random_matrix_5x5)
print(f"\nСереднє значення: {mean_value}")
print(f"Сума елементів, які менше середнього значення: {sum_below_mean}")


Масив:
[[0.07338153 0.03749165 0.76048825 0.16044906 0.6559936 ]
 [0.56243776 0.34001574 0.51584621 0.02494991 0.52983575]
 [0.41220094 0.56043541 0.65469617 0.32280407 0.78151701]
 [0.35173801 0.73768995 0.72566052 0.96063923 0.42801348]
 [0.03084042 0.39307323 0.4852669  0.47327986 0.17530439]]

Середнє значення: 0.44616196207815584
Сума елементів, які менше середнього значення: 2.750262427352303


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими
числами від 1 до 30 та виконайте на них поелементні операції додавання, віднімання
та множення.

In [7]:
import numpy as np

array1 = np.random.randint(1, 31, 5)
array2 = np.random.randint(1, 31, 5)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Перший масив:")
print(array1)
print("\nДругий масив:")
print(array2)

print("\nРезультат поелементного додавання:")
print(addition)
print("\nРезультат поелементного віднімання:")
print(subtraction)
print("\nРезультат поелементного множення:")
print(multiplication)


Перший масив:
[15 13 26  7 25]

Другий масив:
[25  5 28  3 14]

Результат поелементного додавання:
[40 18 54 10 39]

Результат поелементного віднімання:
[-10   8  -2   4  11]

Результат поелементного множення:
[375  65 728  21 350]


Створіть дві матриці 3x3, заповніть їх довільними дійсними числами від 0 до 1 та
знайдіть їх добуток

In [8]:
import numpy as np

matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)

product = np.dot(matrix1, matrix2)

print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)

print("\nДобуток матриць:")
print(product)


Перша матриця:
[[0.4854045  0.86805776 0.27653539]
 [0.8487806  0.39776047 0.14670851]
 [0.46471022 0.25344318 0.25094478]]

Друга матриця:
[[0.20365888 0.98271357 0.2686146 ]
 [0.74169883 0.86641672 0.25201722]
 [0.44138797 0.92937985 0.7341829 ]]

Добуток матриць:
[[0.86475376 1.48611977 0.5521798 ]
 [0.53263556 1.31508248 0.43594823]
 [0.39338488 0.90948747 0.37293936]]


Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.

In [9]:
import numpy as np

np.random.seed(0)

matrix1 = np.random.randint(1, 6, size=(2, 3))
print("Матриця 2x3:")
print(matrix1)

matrix2 = np.random.randint(1, 6, size=(3, 2))
print("\nМатриця 3x2:")
print(matrix2)

result = np.dot(matrix1, matrix2)
print("\nРезультат множення матриць:")
print(result)


Матриця 2x3:
[[5 1 4]
 [4 4 2]]

Матриця 3x2:
[[4 3]
 [5 1]
 [1 5]]

Результат множення матриць:
[[29 36]
 [38 26]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 10 та знайдіть її обернену матрицю

In [10]:
import numpy as np

np.random.seed(0)

matrix = np.random.randint(1, 11, size=(3, 3))
print("Оригінальна матриця 3x3:")
print(matrix)

det = np.linalg.det(matrix)
if det == 0:
    print("\nМатриця є виродженою і не має оберненої матриці.")
else:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)


Оригінальна матриця 3x3:
[[ 6  1  4]
 [ 4  8 10]
 [ 4  6  3]]

Обернена матриця:
[[ 0.16363636 -0.09545455  0.1       ]
 [-0.12727273 -0.00909091  0.2       ]
 [ 0.03636364  0.14545455 -0.2       ]]


Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та транспонуйте її.

In [11]:
import numpy as np

np.random.seed(0)

matrix = np.random.rand(5, 5)
print("Оригінальна матриця 5x5:")
print(matrix)

transposed_matrix = np.transpose(matrix)
print("\nТранспонована матриця:")
print(transposed_matrix)


Оригінальна матриця 5x5:
[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]]

Транспонована матриця:
[[0.5488135  0.64589411 0.79172504 0.0871293  0.97861834]
 [0.71518937 0.43758721 0.52889492 0.0202184  0.79915856]
 [0.60276338 0.891773   0.56804456 0.83261985 0.46147936]
 [0.54488318 0.96366276 0.92559664 0.77815675 0.78052918]
 [0.4236548  0.38344152 0.07103606 0.87001215 0.11827443]]


Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими цілими числами в діапазоні від -5 до 5, а вектор - випадковими дійсними
числами від 0 до 1 і знайдіть добуток матриці на вектор

In [12]:
import numpy as np

np.random.seed(0)

matrix = np.random.randint(-5, 6, size=(3, 4))
print("Матриця 3x4:")
print(matrix)

vector = np.random.rand(4, 1)
print("\nВектор 4x1:")
print(vector)

result = np.dot(matrix, vector)
print("\nРезультат множення матриці на вектор:")
print(result)


Матриця 3x4:
[[ 0 -5 -2 -2]
 [ 2  4 -2  0]
 [-3 -1  2  1]]

Вектор 4x1:
[[0.05671298]
 [0.27265629]
 [0.47766512]
 [0.81216873]]

Результат множення матриці на вектор:
[[-3.94294917]
 [ 0.2487209 ]
 [ 1.32470374]]


Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
від 0 до 1, і знайдіть добуток матриці на вектор

In [13]:
import numpy as np

np.random.seed(0)

matrix = np.random.rand(2, 3)
print("Матриця 2x3:")
print(matrix)

vector = np.random.rand(3, 1)
print("\nВектор 3x1:")
print(vector)

result = np.dot(matrix, vector)
print("\nРезультат множення матриці на вектор:")
print(result)


Матриця 2x3:
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]

Вектор 3x1:
[[0.43758721]
 [0.891773  ]
 [0.96366276]]

Результат множення матриці на вектор:
[[1.45880096]
 [1.23866193]]


Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть суму всіх елементів обох матриць

In [14]:
import numpy as np

np.random.seed(0)

matrix1 = np.random.randint(1, 11, size=(3, 3))
print("Перша матриця 3x3:")
print(matrix1)

matrix2 = np.random.randint(1, 11, size=(3, 3))
print("\nДруга матриця 3x3:")
print(matrix2)

sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)
total_sum = sum_matrix1 + sum_matrix2

print("\nСума всіх елементів першої матриці:")
print(sum_matrix1)

print("\nСума всіх елементів другої матриці:")
print(sum_matrix2)

print("\nСума всіх елементів обох матриць:")
print(total_sum)


Перша матриця 3x3:
[[ 6  1  4]
 [ 4  8 10]
 [ 4  6  3]]

Друга матриця 3x3:
[[5 8 7]
 [9 9 2]
 [7 8 8]]

Сума всіх елементів першої матриці:
46

Сума всіх елементів другої матриці:
63

Сума всіх елементів обох матриць:
109


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть різницю їх елементів.


In [15]:
import numpy as np

np.random.seed(0)

matrix1 = np.random.randint(1, 11, size=(2, 2))
print("Перша матриця 2x2:")
print(matrix1)

matrix2 = np.random.randint(1, 11, size=(2, 2))
print("\nДруга матриця 2x2:")
print(matrix2)

difference = matrix1 - matrix2
print("\nРізниця між відповідними елементами матриць:")
print(difference)


Перша матриця 2x2:
[[6 1]
 [4 4]]

Друга матриця 2x2:
[[ 8 10]
 [ 4  6]]

Різниця між відповідними елементами матриць:
[[-2 -9]
 [ 0 -2]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 5 та знайдіть кількість парних елементів матриці.

In [16]:
import numpy as np

np.random.seed(0)

matrix = np.random.randint(1, 6, size=(3, 3))
print("Матриця 3x3:")
print(matrix)

even_count = np.sum(matrix % 2 == 0)
print("\nКількість парних елементів матриці:")
print(even_count)


Матриця 3x3:
[[5 1 4]
 [4 4 2]
 [4 3 5]]

Кількість парних елементів матриці:
5


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму кубів елементів
кожного рядка матриці

In [17]:
import numpy as np

np.random.seed(0)

matrix = np.random.uniform(-1, 1, size=(4, 4))
print("Матриця 4x4:")
print(matrix)

cubes = np.power(matrix, 3)

sum_of_cubes = np.sum(cubes, axis=1).reshape(-1, 1)
print("\nВектор-стовпчик, що містить суму кубів елементів кожного рядка:")
print(sum_of_cubes)


Матриця 4x4:
[[ 0.09762701  0.43037873  0.20552675  0.08976637]
 [-0.1526904   0.29178823 -0.12482558  0.783546  ]
 [ 0.92732552 -0.23311696  0.58345008  0.05778984]
 [ 0.13608912  0.85119328 -0.85792788 -0.8257414 ]]

Вектор-стовпчик, що містить суму кубів елементів кожного рядка:
[[ 0.0900528 ]
 [ 0.50039175]
 [ 0.98357664]
 [-0.57526483]]


**Висновок:** виконав 15 завдань з масивами та матрицями за допомогою бібліотеки NumPy у Python.